String cachedOnBoardingData="onBoarding";
const String cartDB="CartDB.db";
const String tableCartProduct="cartProduct";
const String columnName="name";
const String columnQuantity="quantity";
const String columnPrice="price";
const String columnImage="image";
const String columnId="id";
const String cachedUserData="user";
